version: "3.7"

services:
  # accessible at //legioncore-db:3306 inside the swarm
  legioncore-db:
    image: mysql:5.6
    restart: always
    volumes:
      # store database outside the container
      - ../../../data/legion/legioncore/database:/var/lib/mysql:delegated
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ascent
      MYSQL_ROOT_HOST: '%'
  authserver:
    image: build:legioncore
    volumes:
      # store database outside the container
      - ../../../data/legion/legioncore/data:/data
      - ../../../install/legioncore:/install
    entrypoint: bash -c 'sleep 10 && /install/bin/bnetserver'
    working_dir: /install/bin
    tty: true # Prevent prompt from spamming stdout
    stdin_open: true
    depends_on:
      - "legioncore-db"
    ports:
      - 8085:8085